flags:
  transformers-compat:
    five-three: true
packages:
- .
extra-deps:
- HUnit-1.6.0.0
- QuickCheck-2.12.4
- ansi-terminal-0.9.1
- ansi-wl-pprint-0.6.9
- call-stack-0.1.0
- clock-0.7.2
- colour-2.3.4
- erf-2.0.0.0
- hashable-1.2.7.0
- hspec-2.5.6
- hspec-core-2.5.6
- hspec-discover-2.5.6
- hspec-expectations-0.8.2
- optparse-applicative-0.14.3.0
- primitive-0.6.4.0
- quickcheck-io-0.2.0
- random-1.1
- setenv-0.1.1.3
- tf-random-0.5
- transformers-0.5.6.2
- transformers-compat-0.6.5
- unordered-containers-0.2.10.0
- vector-0.12.0.1
- vector-algorithms-0.8.0.0

resolver: ghc-8.4.3
